-- SELECT * FROM "student" WHERE age >= 10 AND age < 20;
-- SELECT name FROM "student";
-- SELECT name FROM "student" WHERE name LIKE '_o_';
-- SELECT * FROM "student" WHERE age < student.id;
-- SELECT * FROM "student" ORDER BY age;
